### PR TITLE
nexd: Support unix socket control interface on mac

### LINKED ISSUE #710: nexd: Add nexctl socket interface support on Mac
`nexctl nexd ...` doesn't work on Mac.

### PR DESCRIPTION
**Pull request by russellb**
The only issue with working on mac was using a different default path for the unix socket. Otherwise, it shares the same implementation as Linux.

Closes #710

### CODE REVIEW

File: internal/nexodus/ctlserver_unix.go [hunk 1]
```diff
@@ -1,4 +1,4 @@
-//go:build linux
+//go:build unix
```
Comment (chirino) [inline internal/nexodus/ctlserver_unix.go:1]: I think this can be simplified to:

    //+build linux darwin 

And then you don't need to makefile tricks.

File: internal/nexodus/ctlserver_unix.go [hunk 2]
```diff
@@ -41,9 +43,17 @@ func (ax *Nexodus) CtlServerLinuxStart(ctx context.Context, wg *sync.WaitGroup)
 	})
 }
 
+func UnixSocketPath() string {
+	if runtime.GOOS == Darwin.String() {
+		return unixSocketPathDarwin
```
Comment (chirino) [inline internal/nexodus/ctlserver_unix.go:48]: this could be a platform specific function.

File: internal/nexodus/ctlserver_unix.go (hunk 1 above)
Comment (russellb) [reply internal/nexodus/ctlserver_unix.go]: Ha. I tried to figure that out and tried lots of incorrect ways — comma separated, colon, semicolon …

File: internal/nexodus/ctlserver_unix.go (hunk 2 above)
Comment (russellb) [reply internal/nexodus/ctlserver_unix.go]: Yeah … but it doesn’t look like it’d make a meaningful difference to the binary size. I find this easier to follow than having to jump between files for this simple case. 

It’s probably worth a short design doc that lays out guidelines for the platform specific builds. I wouldn’t think it’s “make platform specific functions any time there is platform specific behavior,” is it? How about “split them when the implementation differs between platforms in non trivial ways and especially if platforms bring in different dependencies as this may have a meaningful  impact on binary size.”
