### PR TITLE
nexd: Add ingress UDP proxy support and IPv6 proxy support

### LINKED ISSUE #702: nexd proxy: Add UDP proxy support
PR #700 included TCP support only. UDP support should be added next.

### LINKED ISSUE #816: proxy: Add IPv6 test coverage
The e2e tests for `nexd proxy` only test IPv4. New tests are needed to ensures IPv6 works in proxy mode, as well.

### LINKED ISSUE #844: Concurrent proxy tests tend to fail after #831 is applied
### Describe the bug

PR #831 disabled running the proxy tests in parallel as they seemed to fail when run in parallel.  

### How to Reproduce

add `t.Parallel()` back into the proxy tests.

### Expected Behavior

tests should pass.

### Deployment Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by russellb**
commit a3b5f4ecae8a94b64ab5d098581b024b470c1b73
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Apr 19 01:28:29 2023 -0400

    nexd: Add IPv6 tunnel IP to the userspace proxy device
    
    The userspace proxy device was configured only with the IPv4 tunnel
    address. This adds the IPv6 address to the device, as well.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit e50511b811e220a126955d15940b364fd76c9dbc
Author: Russell Bryant <rbryant@redhat.com>
Date:   Tue Apr 18 19:21:05 2023 -0400

    nexd: Add ingress UDP proxy support
    
    Add ingress UDP proxy support along with a corresponding e2e test.
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

commit 1a6e05847256715ce8b24a5621ccdddc10b2634d
Author: Russell Bryant <rbryant@redhat.com>
Date:   Wed Apr 19 01:29:30 2023 -0400

    e2e: Add IPv6 TCP proxy test coverage
    
    Test TCP ingress and egress proxy rules that cover:
    
    - v4 to v4
    - v4 to v6
    - v6 to v4
    - v6 to v6
    
    Signed-off-by: Russell Bryant <rbryant@redhat.com>

Closes #702 
Closes #816 
Closes #844

### CODE REVIEW

File: integration-tests/proxy_test.go [hunk 1]
```diff
@@ -130,12 +134,28 @@ func TestProxyEgressUDP(t *testing.T) {
...
+		targets := []target{
+			// v4 client, v4 server
+			{IP: "127.0.0.1", Port: "4242"},
+			// v4 client, v6 server
+			{IP: "127.0.0.1", Port: "4243"},
+			// v6 client, v4 server
+			{IP: "::1", Port: "4242"},
+			// v6 client, v6 server
+			{IP: "::1", Port: "4243"},
+		}
```
Comment (dave-tucker) [inline integration-tests/proxy_test.go:150]:
```suggestion
                targets := []struct {
		    IP   string
		    Port string
	        }{
		    // v4 client, v4 server
		    {IP: "127.0.0.1", Port: "4242"},
		    // v4 client, v6 server
		    {IP: "127.0.0.1", Port: "4243"},
		    // v6 client, v4 server
		    {IP: "::1", Port: "4242"},
		    // v6 client, v6 server
		    {IP: "::1", Port: "4243"},
                }
```

nit: You can use an anonymous struct here

File: integration-tests/proxy_test.go [hunk 2]
```diff
@@ -190,25 +212,35 @@ func TestProxyEgressMultipleRules(t *testing.T) {
...
 
 	// run curl on node2 (to the local proxy) to reach the server on node1
 	ctxTimeout, curlCancel := context.WithTimeout(ctx, 10*time.Second)
 	defer curlCancel()
 	success, err := util.CheckPeriodically(ctxTimeout, time.Second, func() (bool, error) {
-		output, err := helper.containerExec(ctx, node2, []string{"curl", "-s", "http://127.0.0.1"})
-		if err != nil {
-			helper.Logf("Retrying curl for up to 10 seconds while waiting for peering to finish: %v -- %s", err, output)
-			return false, nil
+		type target struct {
```
Comment (dave-tucker) [inline integration-tests/proxy_test.go:222]: nit: Same as above

File: integration-tests/proxy_test.go [hunk 3]
```diff
@@ -279,9 +311,91 @@ func TestProxyIngress(t *testing.T) {
...
+	wg := sync.WaitGroup{}
+	util.GoWithWaitGroup(&wg, func() {
+		_, _ = helper.containerExec(ctx, node2, []string{"udpong", "4242"})
+	})
+
+	// run a UDP client on node1 to reach the remote udp proxy on node1
+	ctxTimeout, clientCancel := context.WithTimeout(ctx, 10*time.Second)
+	defer clientCancel()
+	success, err := util.CheckPeriodically(ctxTimeout, time.Second, func() (bool, error) {
+		type target struct {
```
Comment (dave-tucker) [inline integration-tests/proxy_test.go:366]: nit: Same again 😆

File: integration-tests/proxy_test.go [hunk 4]
```diff
@@ -322,24 +438,35 @@ func TestProxyIngressMultipleRules(t *testing.T) {
...
-			return false, nil
+		type target struct {
+			IP   string
+			Port string
 		}
-		output2, err := helper.containerExec(ctx, node1, []string{"curl", "-s", fmt.Sprintf("http://%s", net.JoinHostPort(node2IP, "8081"))})
-		if err != nil {
-			helper.Logf("Retrying curl for up to 10 seconds while waiting for peering to finish: %v -- %s", err, output2)
-			return false, nil
+		targets := []target{
```
Comment (dave-tucker) [inline integration-tests/proxy_test.go:452]: nit :Again

**Review by dave-tucker — COMMENTED** [review]
LGTM other than a couple of nits in the test code - mainly a style preference.

File: integration-tests/proxy_test.go (hunk 1 above)
Comment (russellb) [reply integration-tests/proxy_test.go:150]: Oh, nice. Yeah that’s perfect. I’ll change.

Comment (russellb) [reply integration-tests/proxy_test.go]: done!
